package com.example.android.january2022.ui.theme
import androidx.compose.ui.graphics.Color


val md_theme_light_primary = Color(0xFF735c00)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFffe076)
val md_theme_light_onPrimaryContainer = Color(0xFF231b00)
val md_theme_light_secondary = Color(0xFF685e40)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFf1e2bc)
val md_theme_light_onSecondaryContainer = Color(0xFF221b04)
val md_theme_light_tertiary = Color(0xFF45664c)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFc7eccb)
val md_theme_light_onTertiaryContainer = Color(0xFF02210d)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfffbf7)
val md_theme_light_onBackground = Color(0xFF1e1b16)
val md_theme_light_surface = Color(0xFFfffbf7)
val md_theme_light_onSurface = Color(0xFF1e1b16)
val md_theme_light_surfaceVariant = Color(0xFFebe2d0)
val md_theme_light_onSurfaceVariant = Color(0xFF4b4639)
val md_theme_light_outline = Color(0xFF7d7768)
val md_theme_light_inverseOnSurface = Color(0xFFf7f0e7)
val md_theme_light_inverseSurface = Color(0xFF33302a)

val md_theme_dark_primary = Color(0xFFe9c334)
val md_theme_dark_onPrimary = Color(0xFF3c2f00)
val md_theme_dark_primaryContainer = Color(0xFF574500)
val md_theme_dark_onPrimaryContainer = Color(0xFFffe076)
val md_theme_dark_secondary = Color(0xFFd4c6a1)
val md_theme_dark_onSecondary = Color(0xFF383016)
val md_theme_dark_secondaryContainer = Color(0xFF4f462a)
val md_theme_dark_onSecondaryContainer = Color(0xFFf1e2bc)
val md_theme_dark_tertiary = Color(0xFFabd0b0)
val md_theme_dark_onTertiary = Color(0xFF183721)
val md_theme_dark_tertiaryContainer = Color(0xFF2e4e35)
val md_theme_dark_onTertiaryContainer = Color(0xFFc7eccb)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF1e1b16)
val md_theme_dark_onBackground = Color(0xFFe8e2d9)
val md_theme_dark_surface = Color(0xFF1e1b16)
val md_theme_dark_onSurface = Color(0xFFe8e2d9)
val md_theme_dark_surfaceVariant = Color(0xFF4b4639)
val md_theme_dark_onSurfaceVariant = Color(0xFFcec6b4)
val md_theme_dark_outline = Color(0xFF979080)
val md_theme_dark_inverseOnSurface = Color(0xFF1e1b16)
val md_theme_dark_inverseSurface = Color(0xFFe8e2d9)

val seed = Color(0xFFffd747)
val error = Color(0xFFba1b1b)