package com.example.android.january2022.ui.theme
import androidx.compose.ui.graphics.Color


val md_theme_light_primary = Color(0xFF705D00)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFE173)
val md_theme_light_onPrimaryContainer = Color(0xFF221B00)
val md_theme_light_secondary = Color(0xFF675E40)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFEFE2BC)
val md_theme_light_onSecondaryContainer = Color(0xFF211B04)
val md_theme_light_tertiary = Color(0xFF235FA6)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFD5E3FF)
val md_theme_light_onTertiaryContainer = Color(0xFF001B3C)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1D1B16)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1D1B16)
val md_theme_light_surfaceVariant = Color(0xFFEAE2CF)
val md_theme_light_onSurfaceVariant = Color(0xFF4B4639)
val md_theme_light_outline = Color(0xFF7D7767)
val md_theme_light_inverseOnSurface = Color(0xFFF6F0E7)
val md_theme_light_inverseSurface = Color(0xFF33302A)
val md_theme_light_inversePrimary = Color(0xFFE7C435)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF705D00)
val md_theme_light_surfaceTintColor = Color(0xFF705D00)

val md_theme_dark_primary = Color(0xFFE7C435)
val md_theme_dark_onPrimary = Color(0xFF3B2F00)
val md_theme_dark_primaryContainer = Color(0xFF554500)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFE173)
val md_theme_dark_secondary = Color(0xFFD2C6A1)
val md_theme_dark_onSecondary = Color(0xFF373016)
val md_theme_dark_secondaryContainer = Color(0xFF4F462A)
val md_theme_dark_onSecondaryContainer = Color(0xFFEFE2BC)
val md_theme_dark_tertiary = Color(0xFFA7C8FF)
val md_theme_dark_onTertiary = Color(0xFF003061)
val md_theme_dark_tertiaryContainer = Color(0xFF004788)
val md_theme_dark_onTertiaryContainer = Color(0xFFD5E3FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1D1B16)
val md_theme_dark_onBackground = Color(0xFFE8E2D9)
val md_theme_dark_surface = Color(0xFF1D1B16)
val md_theme_dark_onSurface = Color(0xFFE8E2D9)
val md_theme_dark_surfaceVariant = Color(0xFF4B4639)
val md_theme_dark_onSurfaceVariant = Color(0xFFCEC6B4)
val md_theme_dark_outline = Color(0xFF979080)
val md_theme_dark_inverseOnSurface = Color(0xFF1D1B16)
val md_theme_dark_inverseSurface = Color(0xFFE8E2D9)
val md_theme_dark_inversePrimary = Color(0xFF705D00)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFE7C435)
val md_theme_dark_surfaceTintColor = Color(0xFFE7C435)


val seed = Color(0xFFFCD848)
//val seed = Color(0xFFffd747)
val error = Color(0xFFba1b1b)